# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               Nxgr
tagline:             ''
description:         'A blogging experimentation, mostly about reverse engineering and CTF.'
url:                 https://nxgr.github.io
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Nxgr
  url:               https://twitter.com/Nxgr_l
  email:             nxgr.infosec@gmail.com

# Custom vars
#version:             1.0.0
